# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |docker|
    docker.image = "marboccu/web_server:latest"
    docker.name = "web_server"
    docker.remains_running = true
    docker.ports = ["8080:80"]
  end
end

