# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "webServer"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nginx curl

    echo "<html><body><h1>Hello, DevOps tribe!</h1></body></html>" | sudo tee /var/www/html/index.html

    sudo systemctl restart nginx
  SHELL
end
