Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ansible-dictionary"
  config.vm.network "private_network", ip: "192.168.33.33"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install_pkgs_playbook.yml"
    ansible.compatibility_mode = "2.0"
    ansible.become = true
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "create_users_playbook.yml"
    ansible.compatibility_mode = "2.0"
    ansible.become = true
  end
end
