- name: Build Docker images
  hosts: local
  become: false
  tasks:
    - name: Build Alpine image
      community.docker.docker_image:
        name: alpine:ssh-v1
        build:
          path: ./alpine
        source: build
        
    - name: Build Rocky image
      community.docker.docker_image:
        name: rocky:ssh-v1
        build:
          path: ./rocky
        source: build
