pipeline {
	agent any
	environment {
		DOCKER_REGISTRY = "localhost:5000"
		IMAGE_TAG = "${env.BUILD_ID}"
		PATH = "/usr/local/bin:$PATH"
	}
	stages {
		stage('Print PATH') {
            steps {
                script {
                    sh 'echo $PATH'
                    sh 'which docker || echo Docker not found'
                }
            }
        }
		stage('Build and Push Alpine image') {
			steps {
				dir('formazione_cm/alpine') {
					script {
						def alpine_image = docker.build("${DOCKER_REGISTRY}/alpine:${IMAGE_TAG}")
						alpine_image.push()
					}
				}
			}
		}
		stage('Build and Push Rocky image') {
			steps {
				dir('formazione_cm/rocky') {
					script {
						def rocky_image = docker.build("${DOCKER_REGISTRY}/rocky:${IMAGE_TAG}")
						rocky_image.push()
					}
				}
			}
		}
	}
	post {
		always {
			cleanWs()
		}
	}
}
