apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  labels:
    app: {{ .Values.image.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ .Values.image.name }}
