apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.name" . }}
  labels:
    app: {{ include "flask-app.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: {{ include "flask-app.name" . }}
