apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.image.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: {{ .Values.image.name }}
