pipeline {
	agent { label 'slave' }
	environment {
		DOCKERHUB_CREDENTIALS = 'DockerHub_id'
		DOCKERHUB_ACCOUNT = 'marboccu'
		DOCKERHUB_IMAGE = "${DOCKERHUB_ACCOUNT}/flask-app-example"
	}
	stages {
		stage('Clone repository') {
			steps {
				checkout scm
				script {
					env.GIT_COMMIT = sh(script: "git rev-parse HEAD", returnStdout: true).trim()
					echo "GIT_COMMIT: ${env.GIT_COMMIT}"
				}
			}
		}
		stage('Set docker tag') {
			steps {
				script {
					env.BRANCH_NAME = sh(script: "git rev-parse --abbrev-ref HEAD", returnStdout: true).trim()
                    env.GIT_TAG	 = sh(script: "git describe --tags --abbrev=0 || true", returnStdout: true).trim()

					if (env.GIT_TAG) {
						env.DOCKER_TAG = env.GIT_TAG
					} else if (env.BRANCH_NAME == 'main') {
						env.DOCKER_TAG = 'latest'
					} else if (env.BRANCH_NAME == 'develop') {
						env.DOCKER_TAG = "develop-${env.GIT_COMMIT.take(7)}"
					} else {
						env.DOCKER_TAG = 'temp'
					}
					echo "Docker tag set to: ${env.DOCKER_TAG}"
				}
			}
		}
		stage('Build and Push docker image') {
			steps {
				dir('formazione_sou_k8s') {
					script {
						def myImage = docker.build("${DOCKERHUB_IMAGE}:${env.DOCKER_TAG}")
						docker.withRegistry('', DOCKERHUB_CREDENTIALS) {
							myImage.push()
						}
					}
				}
			}
		}
	}
}
