Vagrant.configure("2") do |config|
  config.vm.define "node" do |node|
    node.vm.box = "rockylinux/9"
    node.vm.hostname = "node"

    node.vm.network "private_network", ip: "192.168.10.10", netmask: "255.255.255.0"
    node.vm.network "forwarded_port", guest: 8080, host: 8081
    
    node.vm.provision "shell", inline: <<-SHELL
    # Abilito il forwarding sulla VM 
    echo 1 > /proc/sys/net/ipv4/ip_forward
    # regola NAT che maschera l'IP del traffico in uscita da rete Docker quando destinato a subnet
    iptables -t nat -A POSTROUTING -s 192.168.100.0/24 -d 10.0.2.0/24 -j MASQUERADE
    # configuro il forwarding del traffico verso e dalla porta 6443, usata dall'API di kub 
    iptables -A FORWARD -s 192.168.100.0/24 -d 10.0.2.15 -p tcp --dport 6443 -j ACCEPT
    iptables -A FORWARD -d 192.168.100.0/24 -s 10.0.2.15 -p tcp --sport 6443 -j ACCEPT
    SHELL

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "setup_playbook.yml"
      ansible.compatibility_mode = "2.0"
      ansible.config_file = "ansible.cfg"
      ansible.vault_password_file = "vault_pwd.txt"
      ansible.become = true
    end

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

  end
end
