# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/bionic64"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.56.10"
    node1.vm.provision "docker"
    node1.vm.provision "shell", path: "setup.sh", args: ["node1"]
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/bionic64"
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.56.11"
    node2.vm.provision "docker"
    node2.vm.provision "shell", path: "setup.sh", args: ["node2"]
  end
end
