Vagrant.configure("2") do |config|
  config.vm.define "node" do |node|
    node.vm.box = "rockylinux/9"
    node.vm.hostname = "node"

    node.vm.network "private_network", ip: "192.168.10.11", netmask: "255.255.255.0"

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "setup_playbook.yml"
      ansible.compatibility_mode = "2.0"
      ansible.config_file = "ansible.cfg"
      ansible.become = true
    end

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

  end
end
