- name: Using Jinja2 templates
  hosts: local
  become: true
  vars:
    user: martinaboccuzzi
    env: production
    whitelist_users: ['lollo', 'pippo', 'pluto']
  tasks:
    - name: add settings from template to limits.conf
      ansible.builtin.blockinfile:
        path: /etc/security/limits.conf
        block: |
          {{ lookup('ansible.builtin.template', 'templates/limits.j2') }}
        insertafter: EOF
        create: true
      
    - name: grant access to users from template
      ansible.builtin.blockinfile:
        path: /etc/security/access.conf
        block: |
          {{ lookup('ansible.builtin.template', 'templates/access.j2') }}
        insertbefore: '- : ALL : ALL'
        create: true
    
- name: Using Jinja2 for Docker
  hosts: local
  become: true
  vars:
    base_image: "alpine:latest"
    maintainer: "marboccu"
    packages: ['python3', 'vim', 'curl']
    command: "python3 app.py"
  tasks:
    - name: create Dockerfile from template
      ansible.builtin.template:
        src: templates/docker.j2
        dest: ./Dockerfile
      
      
